title: Tony Learns Github Pages
author: Anthony Yates
email: tony@yeahright.com
description: > # this means to ignore newlines until "baseurl:"
  An guided tour for creating github pages. What could be more awesome? Not much...
  This is pretty cool. Thanks to those who have made this feature available!

# social links
twitter_username: anthonyyates # DO NOT include the @ character, or else the build will fail!
github_username:  AnthonyYates # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
